### ISSUE TITLE
The numer of categories != 13204

### ISSUE THREAD

**Issue by seanzhuh** [V3Det/V3Det#18]
Hi, when I load `tree = json.load(open('v3det_2023_v1_category_tree.json'))` the `len(tree['categoryid2treeid'])` == 13204, the length of `leafs = [tree['id2name'][tree_id] for tree_id in list(tree['categoryid2treeid'].values())]` is also == 13204, but len(set(leafs)) gives 13175, which means that the mapping from "id2name" gives the same name for different tree ids, so the number of categories is 13175 instead of 13204 claimed in paper?

**Comment by seanzhuh** [comment]
And surprisingly, one of the leaf name is actually "entity" which is the root node

**Comment by V3Det** [comment]
The number of categories is indeed 13204. It is not recommended to use category names as unique identifiers, as many words are polysemous, such as "mouse". Therefore, it is advisable to use assigned IDs (tree ID or category ID) as identifiers instead of category names. In addition, "entity" is indeed a category in the dataset. Due to the high complexity of classification, not all categories in the dataset are leaf nodes.

**Comment by seanzhuh** [comment]
what do you mean by not all categories in dataset are leaf nodes?
________________________________

**Comment by V3Det** [comment]
For example, our dataset includes many types of butterflies, but there are always some butterflies in certain pictures that are not classified within our detailed butterfly categories. Therefore, we still keep the general category of 'butterfly' as a non-leaf node in our dataset.
